### ISSUE TITLE
Customer Crisis

### ISSUE THREAD

**Issue by HopeIvy12** [SchoolOfCode/week-2-debugging-customer-challenge-team11#1]
```[tasklist]
### Tasks
- [x] We want a game where a player takes a guess at a number between 1 and 10
- [x] You should keep score, and if a player guesses correctly, you should add to the score
- [x] You should ask the player if they want to continue the game, and keep playing until they refuse
- [x] First error found on console: syntax error: unexpected taken 'const' 5:3
- [x] fixed the score
- [x] while loop syntax incorrect
- [x] played not true by default
- [x] fixed math.random
- [x] find the range of the guessing from 0-100 to 1-10
- [x] let userguess variable from const to let as its needs to be able to change the value
- [x] Too change score++ from the lose as the score shouldn't go up when we loose.
- [x] let score needs a value of 0
- [x] imbedded if statements correctly
```

**Comment by HopeIvy12** [comment]
We worked out 5:3 mean line 5 column 3 is where the problem starts. The function didn't have the correct syntax of {}

**Comment by HopeIvy12** [comment]
To fix the max guess of 100 to correct range to 1-10.
Math.random() * 100:
Multiplies the random decimal by 100, scaling it to a range of 0 (inclusive) to 100 (exclusive).
so we changed it to Math.random() * 10:
